### ISSUE TITLE
Error creating transactions

### ISSUE THREAD

**Issue by leomp12** [ecomclub/app-wirecard#15]
Seems that the Wirecard authentication headers are not being saved, and this situation is not treated correctly.

We're getting the following error when trying to create transactions, with exception of store #1011, which have the Wirecard credentials already saved on sqlite:

```console
TypeError: Cannot read property 'w_access_token' of undefined
    at internalApi.then.then.auth (/var/nodejs/wirecard/lib/wirecard-order-request.js:24:49)
```

**Comment by leomp12** [comment]
Actually, the Oauth process wasn't completed, so it's natural to don't have the credential, but in this case you shouldn't return the payment methods on list payments, at the truth the Wirecard payment methods aren't available before Oauth completed.

Stop showing payments in this case would prevent the customer to try paying with unavailable payment method, the merchant would know that the app is not configured yet, and it would also prevent the error above.

**Comment by talissonf** [comment]
Okay, I'll fix this in the next commit, I'll also prevent the application from returning payment_list if the application is not completely configured.

**Comment by leomp12** [comment]
Thanks! If you've tested it after the referenced commit we can close this issue
